### PR TITLE
TASK: Add german translation files

### PR DESCRIPTION
**Pull request by daniellienert**

### CODE REVIEW

**Comment by daniellienert** [comment]
Test failures look rather unrelated ..

**Comment by Prometee** [comment]
@daniellienert thanks for this PR, I will merge it when my last commit will fix the build error.

**Comment by Prometee** [comment]
@daniellienert thanks you for your contribution 🎉👍

I also push a new release with your translations :
https://github.com/Prometee/SyliusVIESClientPlugin/releases/tag/v1.0.7

**Comment by daniellienert** [comment]
Thank you @Prometee for the package and the quick response.

**Pull request merged**
